import datos_personales from "./datos_personales";
import direccion_contacto from './direccion_contacto';
import contacto_eemergencia from './contacto_eemergencia';
import conyuge from './conyuge';
import info_familiar from './info_familiar';
import bienes from './bienes';
import info_bancaria from './info_bancaria';
import formacion from './formacion';
import capacitacion from './capacitacion';
import publicaciones from './publicaciones';
import experiencia from './experiencia';
import trabajo from './trabajo';
import notificaciones from './notificacion';

export const datosPersonales = datos_personales;
export const direccionContacto = direccion_contacto;
export const contactoEmergencia = contacto_eemergencia;
export const conyuge_ = conyuge;
export const infoFamiliar = info_familiar;
export const bienes_ = bienes;
export const infoBancaria = info_bancaria;
export const formacion_ = formacion;
export const capacitacion_ = capacitacion;
export const publicaciones_ = publicaciones;
export const experiencia_ = experiencia;
export const trabajo_ = trabajo;
export const notificaciones_ = notificaciones;