input ContactoEmergenciaIn {
    datos_personales_id: ID!,
    nombre: [String]!,
    apellido: [String]!,
    telefono: [String]!,
    identificacion: IdentificacionIn!,
    parentesco: String!,
    provincia: String!,
    canton: String!,
    parroquia: String!,
    dir: DirIn!
}